CREATE TABLE PERSONS(
	person_id SERIAL PRIMARY KEY,
	first_name TEXT NOT NULL,
	last_name TEXT NOT NULL
);

CREATE TABLE USERS(
	user_id TEXT PRIMARY KEY,
	standup_held BOOLEAN NOT NULL,
	cur_speaker INTEGER NOT NULL
);

CREATE TABLE TEAMS(
	team_id SERIAL PRIMARY KEY,
	user_id TEXT REFERENCES USERS(user_id),
	person_id INTEGER REFERENCES PERSONS(person_id)
);
